### ISSUE TITLE
Error with creating new Rope project.

### ISSUE THREAD

**Issue by squ1b3r** [JulianEberius/SublimeRope#1]
I can't create new project because of error 'Exception: No module named default_config'

I just updated to last version with commit that says you fixed it but I still have this error.

**Comment by JulianEberius** [comment]
Hi!

Have you restarted ST2 after pulling? It caches libraries used by plugins, so the changes come into effect only after a restart. I cannot reproduce the error anymore, sorry.

Julian

**Comment by squ1b3r** [comment]
Hi!

Tnx! I should think about it.
