### ISSUE TITLE
SublimeRope disables Sublimes lexical autocompletion

### ISSUE THREAD

**Issue by lenz** [JulianEberius/SublimeRope#12]
Hi Julian,

thank you very much for sharing this great peace of code with us!
I am running in one problem though:
When I enable SublimeRope the default Sublime autocompletions are disabled.
Is there a way to get around this?

Cheers,

Lenz

**Comment by JulianEberius** [comment]
Hi,

You are right, this behaviour was introduced a few weeks ago, and I don't quite like it myself. It is now optional, default off.
So, as soon as package control updates to the newest version (or you pull from Github) this behaviour should change.

Greetings,
Julian
