### ISSUE TITLE
Windows: git.exe is started for every keystroke

### ISSUE THREAD

**Issue by westmark** [JulianEberius/SublimeRope#14]
I recently discovered that git.exe is launched (and immediately terminated) on every keystroke while editing a python-file (including when saving) if any of the following is true:

1) .ropeproject-folder located in same directory as .git-folder
2) Python-file being edited is located in the same directory as .git-folder. No .ropeproject is configured.

Nothing seems to happen when git is started but as you can probably guess it is incredibly annoying to have that window pop up on every keystroke :)

I managed to get rid of this problem temporarily by removing the git-related entries from fscommands.create_fscommands() but I reckon there exist a much better solution.

**Comment by JulianEberius** [comment]
Hi!

Good find. Yes, I found out Rope offers Git integration which checks for the Git version automatically whenever a Rope project is instantiated. 
It should be disabled in the current version on Github or as soon as Package Control updates.

Greetings,
Julian
