### ISSUE TITLE
Virtualenv's site-packages directory layout is different on Windows

### ISSUE THREAD

**Issue by festlv** [JulianEberius/SublimeRope#15]
On Windows, virtualenv creates the following directory layout:
virtualenv_root:
--Lib
----distutils
----encodings
----site-packages
--Scripts
----activate.bat
....

Since site-packages are searched in %s/lib/python*/site-packages, they are not found.
If I add the site-packages directory to .ropeproject/config.py, as prefs.add('python_path', site_packages_path) the plugin seems to work.

**Comment by JulianEberius** [comment]
Ah interesting. Why does Windows always have to be different :-)?
I just pushed a fix (I hope). Could you try creating a new project on Windows again?

Thank you!

**Comment by JulianEberius** [comment]
I guess this is fixed for quite some time now, closing.
