### ISSUE TITLE
Bug: Import Assist for modules outside the project root don't work. 

### ISSUE THREAD

**Issue by ghost** [JulianEberius/SublimeRope#16]
The Import Assist only imports modules that are with in the sublime's project root, but for modules outside the root path of the project ("even the ones that are seen in the python path") this does not work.

For example I have been trying to import assist the django.contrib.auth.models.User class. 

I can type in "from django." and code completion will show all the modules seen in the python path which in short I can introspect paths with ease if I want to write out all my imports manually. Thus so it will show User (global class) when writing my import manually but this is the only time SublimeRope sees any of the django modules/classes etc... Also once I have imported the User Class then I will get a User (import class) code completion option but still that's only I have already imported that class. 

What I'm looking for is that User (global class) is shown as a code completion option before I even import it and when selected as an option in the code completion that it then imports the class. Many other IDE's preforms in this way such as eclipse

Even then when I type User the select Import Assist I would expect that django.contrib.auth.models.User is shown as a option since its in the python path. 

As it is now I am forced to do all my import manually for all modules outside the root of the project even though the modules are seen in the python path.

**Comment by JulianEberius** [comment]
Hi,

You are right. Rope does not offer an easy way to index the whole PYTHONPATH at the moment. I also do not know how the performance would be if it would.
In Ropevim and Ropemacs you have to explicitly set a list of modules that should be indexed, so maybe this would be a first step.

I'll post here again as soon as I have some free time to spend on SublimeRope.

Greetings,
Julian

**Comment by ghost** [comment]
I would be more then happy even if I had to explicitly set each package path in a settings file. At first I thought that's what I had to do. I played with the settings file source_folder and added django as folder to my sublime project thinking it would then index it but it only looked at the root project folder. 

I forgot to mention I think you have done great work and I really appreciate your efforts thus far.

**Comment by westmark** [comment]
I've also run into this problem. I added a bunch of third-party libraries under the folder with .ropeproject and added their src-folders in .ropeproject/config.py. Got no completions. Then I discovered I had to touch(edit and save) every file in those libraries for rope to index them. One of the files was huuuge and caused ST2 for hang for well over 15 seconds, so I fully understand and support the idea of specifying explicit modules to index. 

It would be nice though if those modules could be specified top-level and if they were auto-indexed when config.py is saved. I would even go so far as to suggest having a standalone indexing script which could be run manually outside of ST2.

And I concur with gfxcomplex; great work! SublimeRope is a life saver.

**Comment by glyph** [comment]
It would be nice if rope provided some command-line tools to do this indexing, because having set it up with explicit configuration in both Emacs and Vim I can say that the performance is pretty terrible.  Would it be possible to maybe do this indexing in a subprocess?

**Comment by glyph** [comment]
I discovered that you can generate the indexes externally, and SublimeRope will display the completions regardless.  Such a script looks something like:

```
from rope.base.project import Project
from rope.contrib.autoimport import AutoImport
p = Project(".")
AutoImport(p).generate_modules_cache(["os", "os.path", ...])
p.sync()
```

You can also do this by just using a different editor's Rope support (vim, emacs) and giving it an appropriate autoimport list.

**Comment by DamnWidget** [comment]
Hi glyph.

I just added this feature to my fork at https://github.com/DamnWidget/SublimeRope  

Could you test it before I request a pull for integration with Julian branch? I'm not sure it's working in the way you suggested.

In order to make it work you just should add a list of modules in the SublimeRope settings file and generate the modules cache.

Greetings.

**Comment by glyph** [comment]
Is there a convenient way to tell Package Control to switch where it's getting one package from for a little while, or do I just have to remove the package and then manually check out your fork with git?

**Comment by DamnWidget** [comment]
You can just clone the git repo in your Packages directory with another name and then disable the Julian SublimeRope, then just disable my fork and enable Julian plugin again.

**Comment by glyph** [comment]
Oh right, by adding to the `ignored_packages` preference.  I'll check this out a little later.

**Comment by DamnWidget** [comment]
Seems like Julian already merged this feature in the main branch of this repository.

**Comment by JulianEberius** [comment]
It seemed to work fine for me, so I merged it. Could you report if you encounter any problems?

**Comment by JulianEberius** [comment]
Seems to work now -> closed.

**Comment by mosnicholas** [comment]
This isn't working for me still –– I don't get auto-completion on modules outside the directory. Is there anything I need to do to fix it locally?

Thanks for the product also, it's great!
