### ISSUE TITLE
SublimeRope doesn't find virtualenv when creating new project though it's there

### ISSUE THREAD

**Issue by cmsimike** [JulianEberius/SublimeRope#17]
Did not find a virtualenv at /Users/mike/Development/dev.example.com.
Looking for path matching /Users/mike/Development/dev.example.com/lib/python*/site-packages

but in my terminal, I can say
cd /Users/mike/Development/dev.example.com/lib/python2.7/site-packages and change into that directory. How can I go about debugging my issue or help you debug this issue?

**Comment by zbuc** [comment]
This looks the same as https://github.com/JulianEberius/SublimeRope/pull/18 give that patch a shot, it worked for me when I had this problem

**Comment by JulianEberius** [comment]
I guess this is fixed now. Reply if not!

Julian
