### ISSUE TITLE
autocomplete do not work in the new released sublime text 2.0

### ISSUE THREAD

**Issue by abadcafe** [JulianEberius/SublimeRope#24]
Either .ropeproject existed or not.

OS: arch linux x86_64.

**Comment by zilvinasu** [comment]
It lags editor to death when you try to write something like "from" in python code I write first letter "f" and it lags.

**Comment by JulianEberius** [comment]
Hi,

Sorry I cannot reproduce this behavior. It worked on my old install, and I just did a clean install of 2.0 (removed all prefs, packages etc) and just installed SublimeRope from package control. I could not find your problem, so I will need more information, e.g. which operating systems do you use? Does the error persist after a clean install? Is there any feedback in ST2's console?

Regards,
Julian

**Comment by zilvinasu** [comment]
Hmm nothing, might be problems with my OS then sorry

**Comment by abadcafe** [comment]
I am using archlinux with kernel 3.4.4-2 on x86_64.

I just removed old ~/.config/sublime-text-2, and reinstalled sublime text 2.0, package controller and SublimeRope.

Now, I type codes below:

<pre>
#!/usr/bin/env python3

class aaaa:

    def __init__(self):
        pass
    
    def bbbb(self):
        pass

cccc = aaaa()
cccc.
</pre>

In sublime text 2 build 2181, it pop up a menu includes bbbb(), but there is no menu In sublime text 2.0.

**Comment by abadcafe** [comment]
OK, I found the reason.

If I set "auto_complete" as false, I can not get any completion, even press ctrl + space. But if i set "auto_complete" as true, the plugin works fine.

So, the bug exactly is, ctrl + space is not behave as it used to be. In build 2181, ctrl + space can trigger complete.

**Comment by JulianEberius** [comment]
So, I guess this is closed then.

**Comment by samishchandra** [comment]
how to make the auto_complete window popup after "." (<dot> character). Its hard to use <ctrl+space> to popup the window every time. Is there a way to automatically pop it.

**Comment by JulianEberius** [comment]
Hi,

There is something about this feature in the docs:
http://sublimerope.readthedocs.org/en/latest/auto_completion.html#howto-get-autocompletion-on-dot-typing

Julian

**Comment by samishchandra** [comment]
Thanks JulianEberius for the reply, do you know how to provide auto completions for inbuilt library functions in python
