### ISSUE TITLE
Lots of duplicated code and "numbered lines" in sublime_rope.py

### ISSUE THREAD

**Issue by OscarL** [JulianEberius/SublimeRope#26]
See [sublime_rope.py at line 510](https://github.com/JulianEberius/SublimeRope/blob/753f1f0ba83a7686a6c556ce9e2a43c6e6374e07/sublime_rope.py#L510) onwards.

That appeared in the 753f1f0ba83a7686a6c556ce9e2a43c6e6374e07 commit.

It seems like a copy-paste or diff-patch issue to me (notice the "numbered lines", and that almost all the "sublime.TextCommand"s are present twice).

**Comment by OscarL** [comment]
Note that due to the redefined TextCommands the context cache is not used as intended (the redefined ones still use "ropemate.RopeContext(view)" instead of "ropemate.context_for(view)").

**Comment by JulianEberius** [comment]
Strange, I was pretty sure I eliminated this copy-pasta before commiting... 

Well I hope it is fixed now. Thanks for reviewing!
