### ISSUE TITLE
SublimeRope is broken

### ISSUE THREAD

**Issue by brabadu** [JulianEberius/SublimeRope#28]
For any action, that I try to perform with SublimeRope I get console

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./sublime_rope.py", line 531, in run
    ctx = ropemate.context_for(self.view)
AttributeError: 'module' object has no attribute 'context_for'
```

SublimeRope is installed with PackageManager, ST2 version is 2.0

**Comment by JulianEberius** [comment]
Hi,

Can you try to just restart ST2? I think it automatically reloads the plugin, but not the imported modules (in this case ropemate).

Julian

**Comment by brabadu** [comment]
Dough! It helped.

Thanks a lot :)
