### ISSUE TITLE
Rope: Show Documentation doesn't work once I've typed some parentheses

### ISSUE THREAD

**Issue by glyph** [JulianEberius/SublimeRope#34]
Whenever I use the "show documentation" function, it's almost always because I want to remember the order of arguments to a function.  Which means I type 'foo_bar(' and then realize that I want the docs.  But, at that point it's too late: SublimeRope doesn't see the cursor over a word, it sees it between empty parentheses and gives up.

It would be nice if it would search to the left just one character so I didn't have to manually help it along.  (In Emacs and Vim, "rope-show-calltip" works even if you're already in parens after the function name.)

**Comment by JulianEberius** [comment]
Should be fixed now.
