### ISSUE TITLE
Restructure refactoring works only on GNU/Linux

### ISSUE THREAD

**Issue by DamnWidget** [JulianEberius/SublimeRope#36]
I just adviced that refactor restructure works only on GNU/Linux.

Seems like in Windows and Mac OS X platforms view calls must be done in main_thread only. You can use sublime.set_timeout to wrapper the calls

**Comment by JulianEberius** [comment]
Can anyone confirm that they work? I never use this feature myself ;-)

**Comment by DamnWidget** [comment]
It's working for me.
