### ISSUE TITLE
"show documentation" takes focus

### ISSUE THREAD

**Issue by glyph** [JulianEberius/SublimeRope#38]
When I show the documentation, I am usually doing it so I will know what arguments to pass; the window currently takes focus, which means that I have to manually move my cursor back.  It would be nice if it could pop up without interrupting my typing.

**Comment by DamnWidget** [comment]
Usually I hit ESC key to return back to the buffer when I get the info.

I'll take a look anyway.

**Comment by glyph** [comment]
@DamnWidget Exactly - I don't want to hit ESC because I want to keep the docs _open_ and continue to referring to them as I add in arguments.  This is useful only for functions with long/complex argument lists, but if the argument list is short and simple then I generally remember it and don't need to look at the docs in the first place :).

**Comment by DamnWidget** [comment]
I just fix it, jus wait for Julian to merge.

I love twisted, btw :P

**Comment by DamnWidget** [comment]
I think this issue should be closed since was fixed in pull requets #39
