### ISSUE TITLE
Missing modules in configuration file

### ISSUE THREAD

**Issue by mobedigg** [JulianEberius/SublimeRope#44]
System: Win7
When I select  "Regenarate Global Module Cache" I got error Missing modules in configuration file.
With Regenerate Project Cache all ok.

**Comment by DamnWidget** [comment]
Did you add the "rope_autoimport_modules" list in settings section of your project file?

**Comment by mobedigg** [comment]
No, I didn't.

**Comment by DamnWidget** [comment]
That's the problem then. You should add the modules list in your project configuration file adding the settings section if it doesn't ezxists yet:
"settings":
{
    "rope_autoimport_modules":
    [
        "twisted._",
        "numpy._",
        "libsaas.*"
        ...
    ]
}

**Comment by mobedigg** [comment]
Yes, my mistake. You are right.

**Comment by DamnWidget** [comment]
Don't worry. 

:+1:

**Comment by JulianEberius** [comment]
I love it when problems sort themselves out before I have to do anything ;-)
Anyway, lesson learned: SublimeRope needs clearer documentation, and the different completion mechanisms and caches (PYTHONPATH-based, Module Cache, Global Module Cache) should be consolidated in both code and documentation.

Julian

**Comment by DamnWidget** [comment]
I agree with you @JulianEberius so I'm already working in a new Sphinx based WiKi. I will pull a request when done.

Greetings.
