### ISSUE TITLE
how to configure sublme rope to enable syntax auto complete

### ISSUE THREAD

**Issue by openxmpp** [JulianEberius/SublimeRope#56]
Hi , I use sublime for coding ,it 's really cool . I have installed sublimerope & sublime lint from sublime package control, I want to konw how to configure sublimerope so it can do syntax auto-complete.
For example , I have installed pyqt with python2.7.
using eclipse , when I input the following:
     from PyQt4. ( when I input the dot , a list of possible match will be showed) . How to do this with sublimerope?
    I searched the closed issuses ,and haven't found any way works ...

**Comment by DamnWidget** [comment]
Hi @openxmpp 

You have all the related documentation here http://sublimerope.readthedocs.org/en/latest/auto_completion.html

By the way, if you are using PyQt4 maybe you should be interested in use my plugin for PyQt4 (and PySide) called "PySide" https://github.com/DamnWidget/SublimePySide.

You can install it through Package Control.

**Comment by JulianEberius** [comment]
I hope the documentation could help you... I will try to make SublimeRope a bit more self-explanatory and easy-to-use in the future. For now, issue closed.
