### ISSUE TITLE
Saving a project prompts to fix imports

### ISSUE THREAD

**Issue by drewcrawford** [JulianEberius/SublimeRope#74]
Whenever I 'save' a file, using either command-s or file->save, I get a prompt asking me to fix the imports.  

The issue can be resolved by uninstalling SublimeRope, but it comes back when it is reinstalled.

**Comment by JulianEberius** [comment]
Hi,

Please check the settings and the documentation...
This is actually not a bug, but a feature (although it is one I don't use myself, not sure when it became default).
The setting you're lookingfor is called "use_autoimport_improvements", just set it to false.

Julian
