### ISSUE TITLE
add auto-import command

### ISSUE THREAD

**Issue by glyph** [JulianEberius/SublimeRope#8]
It'd be great to have access to the auto-import functionality that ropemacs and ropevim provide, where you can position the cursor over an undefined symbol and have it automatically insert the import at the appropriate place, or even better, to have the import automatically inserted when it's selected as a completion.

**Comment by JulianEberius** [comment]
Hi,

This was added in the latest version as a command you can call manually with some word under your cursor. 

I see no way to perform an additional action when the user selects a certain completion with the current API, so I can't think of a way to do it automatically "on completion" at the moment. Maybe there will be an API event for this in the future.

Greetings,
Julian

**Comment by glyph** [comment]
It's probably possible to guess, by having an on_modified and/or on_selection_modified that cooperate with an on_query_completions to determine when one was chosen.  But, better would of course be to just file a bug against Sublime and wait for that event to be implemented for real.

Thanks so much for implementing this though!

**Comment by glyph** [comment]
I'm invoking this as the command "Rope: Import Assist" but it doesn't seem to work.  I don't see any feedback on the console or in the status area, either.  Any clues as to what might be going wrong?  Everything else seems okay.

**Comment by JulianEberius** [comment]
Are you working in a Rope project? At the moment it only completes globals from modules in your current Rope project (so not even modules on the PYTHONPATH work at the moment, see issue #16)

**Comment by glyph** [comment]
Hrm.  Looks like I might have been expecting built-in names to auto-import; I thought I'd tried names within my project too, but double-checking now I can see that the import assist functionality works nicely for those.  It would still be nice to get some feedback in the status line or something, for the cases where it doesn't come up with any options :).  I'll keep an eye on #16 for now, thanks.
