### ISSUE TITLE
'Invalid Syntax' error with end="" keyword within print() function

### ISSUE THREAD

**Issue by appqi** [JulianEberius/SublimeRope#82]
Hello, I'd like to print some numbers without newline.
Python2: print x,               # The comma suppresses newline
Python3: print(x, end=" ")  # Adds a space instead of a newline

If I try the following: 

for number in range(5):
    print(number, end=" ")

It works perfectly in Python3 (I get the result without errors) but SublimeRope shows an error 'invalid syntax'
![image](https://f.cloud.github.com/assets/4772491/1089435/f858e85a-1643-11e3-9421-6ced63cc9945.png)

Is there any workaround?

EDIT: I use SublimeText 2.0.2 Build 2221, Python3.3.2 32bit, Windows 7 x64
EDIT2: Same problem with SublimeLinter (https://github.com/SublimeLinter/SublimeLinter/issues/561)

**Comment by JulianEberius** [comment]
Hi, 

Sorry for the late reply. No there is no easy way to fix this in SublimeRope, as it runs inside ST2, which uses Python 2 internally. This is probably the reason you get the same error in SublimeLinter. 

The best solution would be to upgrade to the ST3 Beta and use my rewritten Python Plugin SublimePythonIDE which works on ST3 and uses a different architecture (external Python process using the same version as your project).

Regards,
Julian
