### ISSUE TITLE
add "jump to global" command

### ISSUE THREAD

**Issue by glyph** [JulianEberius/SublimeRope#9]
ropemacs and ropevim supply a "jump to global" command which allows the user to interactively enter the unqualified name of a global at a prompt, rather than import the fully qualified global in a buffer in order to jump to its definition.  That would be nice to have.

**Comment by JulianEberius** [comment]
Yes, this is certainly a useful feature. I implemented it in the current version of the plugin.

**Comment by glyph** [comment]
Thanks!
